apiVersion: v1
kind: ConfigMap
metadata:
  name: academins-config
  namespace: academins
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://academins-postgres:5432/academins-db
  SPRING_RABBITMQ_HOST: "rabbitmq.rabbitmq.svc.cluster.local"
  SPRING_RABBITMQ_PORT: "5672"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka.eureka-server.svc.cluster.local:8761/eureka/"
  init.sql: |
    CREATE DATABASE "academins-db";