apiVersion: apps/v1
kind: Deployment
metadata:
  name: academins-deployment
  namespace: academins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academins
  template:
    metadata:
      labels:
        app: academins
    spec:
      containers:
        - name: academins
          image: hugobpc/mtds_2025_2026-academins:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: academins-config
            - secretRef:
                name: academins-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 12
            periodSeconds: 10
            failureThreshold: 6
