apiVersion: v1
kind: Secret
metadata:
  name: schedules-secret
  namespace: schedules
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "myuser"
  SPRING_DATASOURCE_PASSWORD: "secret"
  SPRING_RABBITMQ_USERNAME: "user"
  SPRING_RABBITMQ_PASSWORD: "123"
