apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedules-deployment
  namespace: schedules
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedules
  template:
    metadata:
      labels:
        app: schedules
    spec:
      containers:
        - name: schedules
          image: hugobpc/mtds_2025_2026-schedules:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: schedules-config
            - secretRef:
                name: schedules-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 12
            periodSeconds: 10
            failureThreshold: 6
