apiVersion: v1
kind: Service
metadata:
  name: assessments-planning-postgres
  namespace: assessments-planning
spec:
  selector:
    app: assessments-planning-postgres
  ports:
    - port: 5432
      targetPort: 5432
