apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assessments-planning-postgres-pvc
  namespace: assessments-planning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
