apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: applications-postgres-pvc
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
