services:
  db:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=schedules-db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d schedules-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12.9-management-alpine
    container_name: rabbit_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/schedules-db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=123
#      - SPRING_REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
#      - redis


volumes:
  rabbitmq_data:
    driver: local
  db_data:
    driver: local



# Não precisa de network, o compose cria uma rede padrão para os serviços se comunicarem.