  apiVersion: v1
  kind: Service
  metadata:
    name: assessments-planning-mongo
    namespace: assessments-planning
  spec:
    selector:
      app: assessments-planning-mongo
    ports:
      - port: 27017
        targetPort: 27017
    type: ClusterIP
