apiVersion: v1
kind: ConfigMap
metadata:
  name: assessments-planning-mongo-init
  namespace: assessments-planning
data:
  init.js: |
    // Script executado apenas na primeira criação da base de dados
    db = db.getSiblingDB("assessments_content_db");
    db.createCollection("init_collection");