apiVersion: v1
kind: Service
metadata:
  name: assessments-mongo
  namespace: assessments
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: assessments-mongo