apiVersion: v1
kind: ConfigMap
metadata:
  name: grade-report-config
  namespace: grade-report
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://grade-report-postgres:5432/grade-report-db
  SPRING_APPLICATION_NAME: "GradeReport"
  SPRING_RABBITMQ_HOST: "rabbitmq.rabbitmq.svc.cluster.local"
  SPRING_RABBITMQ_PORT: "5672"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka.eureka-server.svc.cluster.local:8761/eureka/"
  SERVICES_ACADEMINS_URL: "http://academins.academins.svc.cluster.local:8080/api/v1/academins"
  init.sql: |
    CREATE DATABASE "grade-report-db";