apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-report-deployment
  namespace: grade-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-report
  template:
    metadata:
      labels:
        app: grade-report
    spec:
      containers:
        - name: grade-report
          image: hugobpc/mtds_2025_2026-grade-report:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: grade-report-config
            - secretRef:
                name: grade-report-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5