//--------------------------------------------------------------------
// Microserviço de Configuração de Avaliações
// Responsável pela definição da estrutura de avaliação das UCs
//--------------------------------------------------------------------



Table componentes_avaliacao {
  id int [pk, increment]
  unidade_curricular_id int [not null]
  ano_letivo_id int [not null]
  nome varchar(100) [not null]
  peso decimal(5,4) [not null]
  nota_minima decimal(4,2)
  created_at timestamp
  updated_at timestamp
  
  indexes {
    (unidade_curricular_id, ano_letivo_id)
  }

  note: 'Componentes de avaliação de uma unidade curricular (ex: exame, trabalhos, etc)'
}

Table momentos_avaliacao {
  id int [pk, increment]
  componente_id int [ref: > componentes_avaliacao.id]
  titulo varchar(255) [not null, note: 'Título do momento de avaliação']
  data_realizacao timestamp
  duracao_minutos int [note: 'Duração prevista em minutos']
  sala varchar(50) [note: 'Local de realização']
  estado estado_momento [not null, default: 'AGENDADO']
  created_at timestamp
  updated_at timestamp
  
  note: 'Momentos específicos de avaliação dentro de um componente (onde se vai realizar o exame, teste, etc)'
}


Enum estado_momento {
  AGENDADO [note: 'Programado para realização']
  EM_CURSO [note: 'Em andamento']
  REALIZADO [note: 'Concluído']
  CANCELADO [note: 'Cancelado']
}