apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  namespace: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: hugobpc/mtds_2025_2026-notifications:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-config
            - secretRef:
                name: notifications-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
            successThreshold: 1