apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
  namespace: notifications
type: Opaque
stringData:
  SPRING_MONGO_URI: mongodb://notifications-mongo:27017/notifications-db
  SPRING_RABBITMQ_USERNAME: "user"
  SPRING_RABBITMQ_PASSWORD: "123"
