apiVersion: v1
kind: Secret
metadata:
  name: assessments-secret
  namespace: assessments
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "secret"
  SPRING_RABBITMQ_USERNAME: "user"
  SPRING_RABBITMQ_PASSWORD: "123"
  SPRING_MONGO_URI: "mongodb://assessments-mongo-0.assessments-mongo:27017/assessments_logs_db"